#define IDI_ICON_JISHO 1
#define IDI_ICON_KIDNEY 2
#define IDI_ICON_LEFT 3
#define IDI_ICON_RIGHT 4

#define IDF_FONT1 1

#define IDS_TOOLTIP 1

#define IDM_MENU 1

#define IDM_NOTIF_QUIT 1
#define IDM_NOTIF_SETTINGS 2
